name: Test
on: [push]
jobs:
  runTests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby-version: [ 2.7.4 ]
        appraisal:
          - rails_6
          - rails_6.1
          - rails_7
        # include:
        #   - ruby-version: 2.3.8
        #     appraisal: rails-3.2
        #   - ruby-version: 2.3.8
        #     appraisal: rails-4
        #   - ruby-version: 2.6.9
        #     appraisal: rails-5

    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/${{ matrix.appraisal }}.gemfile

    steps:
      - uses: actions/checkout@master
      - name: Install ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - name: Run tests
        run: |
          bundle exec appraisal ${{ matrix.appraisal }} rake test
