name: Test
on: [push]
jobs:
  runTests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby-version: [ 3.4.5 ]
        appraisal:
          - rails_7
          - rails_8.0
        include:
          - ruby-version: 2.3.8
            appraisal: rails_3.2
          # - ruby-version: 2.3.8
          #   appraisal: rails_4
          # - ruby-version: 2.6.10
          #   appraisal: rails_5.2
          # - ruby-version: 2.7.8
          #   appraisal: rails_6
          - ruby-version: 2.7.8
            appraisal: rails_6.1
          - ruby-version: 3.2.8
            appraisal: rails_7.2

    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/${{ matrix.appraisal }}.gemfile

    steps:
      - uses: actions/checkout@master
      - name: Install ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - name: Run tests
        run: |
          bundle exec appraisal ${{ matrix.appraisal }} rake test
